// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// recalc
arma::mat recalc(const arma::umat& labels, const arma::uword nodes, const arma::mat& P, const arma::vec& D, arma::mat input, const double rho);
RcppExport SEXP _corMLPE_recalc(SEXP labelsSEXP, SEXP nodesSEXP, SEXP PSEXP, SEXP DSEXP, SEXP inputSEXP, SEXP rhoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::umat& >::type labels(labelsSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type nodes(nodesSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type P(PSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type D(DSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type input(inputSEXP);
    Rcpp::traits::input_parameter< const double >::type rho(rhoSEXP);
    rcpp_result_gen = Rcpp::wrap(recalc(labels, nodes, P, D, input, rho));
    return rcpp_result_gen;
END_RCPP
}
// adjacency
arma::mat adjacency(const arma::umat& labels, const arma::uword nodes);
RcppExport SEXP _corMLPE_adjacency(SEXP labelsSEXP, SEXP nodesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::umat& >::type labels(labelsSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type nodes(nodesSEXP);
    rcpp_result_gen = Rcpp::wrap(adjacency(labels, nodes));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_corMLPE_recalc", (DL_FUNC) &_corMLPE_recalc, 6},
    {"_corMLPE_adjacency", (DL_FUNC) &_corMLPE_adjacency, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_corMLPE(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
