# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MultLambda <- function(x, v, p) {
    .Call('corMLPE_MultLambda', PACKAGE = 'corMLPE', x, v, p)
}

MultLambdaTrio <- function(x, v) {
    .Call('corMLPE_MultLambdaTrio', PACKAGE = 'corMLPE', x, v)
}

MultLambdaGroups <- function(x, v, n, p) {
    .Call('corMLPE_MultLambdaGroups', PACKAGE = 'corMLPE', x, v, n, p)
}

eigenVals <- function(tau, n) {
    .Call('corMLPE_eigenVals', PACKAGE = 'corMLPE', tau, n)
}

eigenVecs <- function(n) {
    .Call('corMLPE_eigenVecs', PACKAGE = 'corMLPE', n)
}

eigenCount <- function(n) {
    .Call('corMLPE_eigenCount', PACKAGE = 'corMLPE', n)
}

matrixCount <- function(n) {
    .Call('corMLPE_matrixCount', PACKAGE = 'corMLPE', n)
}

matrixVals <- function(lambda, e) {
    .Call('corMLPE_matrixVals', PACKAGE = 'corMLPE', lambda, e)
}

likelihood <- function(v, cnt, l, lcnt, x, y, p, sigma) {
    .Call('corMLPE_likelihood', PACKAGE = 'corMLPE', v, cnt, l, lcnt, x, y, p, sigma)
}

sampleTauSigma <- function(lltausig, iter, tune, e, cnt, lcnt, x, y, p) {
    .Call('corMLPE_sampleTauSigma', PACKAGE = 'corMLPE', lltausig, iter, tune, e, cnt, lcnt, x, y, p)
}

build_index <- function(nr, nc) {
    .Call('corMLPE_build_index', PACKAGE = 'corMLPE', nr, nc)
}

build_pointer <- function(nr, nc) {
    .Call('corMLPE_build_pointer', PACKAGE = 'corMLPE', nr, nc)
}

fill_values <- function(nr, nc, ind, p, R) {
    .Call('corMLPE_fill_values', PACKAGE = 'corMLPE', nr, nc, ind, p, R)
}

all_pairs <- function(p) {
    .Call('corMLPE_all_pairs', PACKAGE = 'corMLPE', p)
}

