# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.factor_cov_cpp <- function(labels, L, K) {
    .Call('_corMLPE_factor_cov', PACKAGE = 'corMLPE', labels, L, K)
}

.recalc_cov_cpp <- function(labels, L, M, stddev, input) {
    .Call('_corMLPE_recalc_cov', PACKAGE = 'corMLPE', labels, L, M, stddev, input)
}

.getCovariate_cov_cpp <- function(labels, nodes) {
    .Call('_corMLPE_getCovariate_cov', PACKAGE = 'corMLPE', labels, nodes)
}

.recalc_cpp <- function(labels, nodes, P, D, input, rho) {
    .Call('_corMLPE_recalc', PACKAGE = 'corMLPE', labels, nodes, P, D, input, rho)
}

.getCovariate_cpp <- function(labels, nodes) {
    .Call('_corMLPE_adjacency', PACKAGE = 'corMLPE', labels, nodes)
}

